/*
 * CQL Clarity — Spec Document Generator
 * -------------------------------------------------
 * Turns an analysis object (from analyzer.js) into an audience-tuned spec
 * document in two modes:
 *   - 'business' : narrative Measure Specification, no code
 *   - 'engineer' : Engineering Intent Brief with code, data matrix, gotchas
 *
 * A spec is a structured list of blocks that can be rendered to Markdown,
 * to safe in-app HTML, or to a standalone printable HTML document. Keeping the
 * blocks structured (not raw HTML) keeps the module DOM-free and testable.
 *
 * Browser: window.CQLSpec.  Node: module.exports.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (root) root.CQLSpec = api;
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  function esc(v) {
    return String(v == null ? '' : v)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#039;');
  }

  // --------------------------------------------------------------- tree helper
  /** booleanLines (indented plain text) -> [{depth, text}] with bullets stripped. */
  function parseTree(lines) {
    return (lines || []).map(line => {
      const m = line.match(/^(\s*)/);
      const depth = Math.floor((m ? m[1].length : 0) / 2);
      const text = line.trim().replace(/^•\s*/, '');
      return { depth: depth, text: text };
    });
  }

  // --------------------------------------------------------------- shared bits
  function metaList(a) {
    const items = [];
    if (a.library.name) items.push('Measure / library: ' + a.library.name + (a.library.version ? ' v' + a.library.version : ''));
    items.push('Data model: ' + a.validation.model);
    if (a.library.context) items.push('Context: ' + a.library.context);
    items.push('Definitions: ' + a.definitions.length);
    items.push('Generated: ' + new Date().toLocaleDateString());
    return items;
  }

  function populationDefs(a) {
    const roled = a.definitions.filter(d => d.populationRole);
    if (roled.length) return roled;
    return a.definitions.filter(d => d.kind !== 'function');
  }

  // ============================================================== BUSINESS
  function buildBusiness(a) {
    const blocks = [];
    const title = (a.library.name || 'Untitled Measure');

    blocks.push({ callout: { kind: 'note', title: 'Draft — verify before use',
      text: 'This specification was generated by structural analysis and inferred intent. It is a starting draft, not an official specification. Confirm populations, value sets, and timing against the source measure and your terminology service.' } });

    blocks.push({ h2: 'Purpose' });
    blocks.push({ p: a.summary.text });

    blocks.push({ h2: 'Who is measured' });
    if (a.populationFlow.narrative) blocks.push({ p: a.populationFlow.narrative });
    const popList = populationDefs(a).map(d => {
      const role = d.populationRole ? d.populationRole + ' — ' : '';
      return role + d.explanation;
    });
    if (popList.length) blocks.push({ ul: popList });

    blocks.push({ h2: 'Eligibility & criteria' });
    populationDefs(a).forEach(d => {
      blocks.push({ h3: d.populationRole ? d.populationRole + ' (" ' + d.name + ' ")' : d.name });
      if (d.booleanLines && d.booleanLines.length) blocks.push({ tree: parseTree(d.booleanLines) });
      else blocks.push({ p: d.explanation });
    });

    if (a.temporalFlows.length) {
      blocks.push({ h2: 'Timing windows' });
      blocks.push({ table: {
        headers: ['Definition', 'Window begins', 'Window ends', 'Requirement'],
        rows: a.temporalFlows.map(w => [w.definition, w.windowBegins, w.windowEnds, w.requirement]),
      } });
    }

    const numerator = a.definitions.find(d => d.populationRole === 'Numerator');
    if (numerator) {
      blocks.push({ h2: 'What counts as compliant' });
      blocks.push({ p: numerator.explanation });
      if (numerator.booleanLines && numerator.booleanLines.length) blocks.push({ tree: parseTree(numerator.booleanLines) });
    }

    const businessFlags = a.reviewFlags.filter(f => f.severity !== 'Info' || /value-set/i.test(f.message));
    if (businessFlags.length) {
      blocks.push({ h2: 'Assumptions & things to confirm' });
      businessFlags.forEach(f => blocks.push({ callout: { kind: f.severity,
        title: f.message + (f.line ? ' (' + f.definition + ', line ' + f.line + ')' : ''),
        text: f.why } }));
    }

    const valueSets = uniq([].concat.apply([], a.definitions.map(d => d.valueSets)));
    const resources = uniq([].concat.apply([], a.definitions.map(d => d.retrieves.map(r => r.resourceType))));
    if (valueSets.length || resources.length) {
      blocks.push({ h2: 'Data used' });
      if (resources.length) blocks.push({ p: 'Clinical record types: ' + resources.join(', ') + '.' });
      if (valueSets.length) blocks.push({ ul: valueSets.map(v => 'Value set: ' + v) });
    }

    return { title: title + ' — Measure Specification', subtitle: 'Business specification (draft)', blocks: blocks };
  }

  // ============================================================== ENGINEER
  function buildEngineer(a) {
    const blocks = [];
    const title = (a.library.name || 'Untitled Library');

    blocks.push({ h2: 'Overview' });
    blocks.push({ p: a.summary.text });
    blocks.push({ ul: metaList(a) });
    blocks.push({ callout: { kind: 'note', title: 'Scope',
      text: 'Structural analysis only. Syntax, ELM translation, value-set contents, and execution are NOT verified here. Treat return types and intent as inferred unless confirmed by a compiler.' } });

    blocks.push({ h2: 'Definitions' });
    a.definitions.forEach(d => {
      blocks.push({ h3: d.name + (d.populationRole ? '  ·  ' + d.populationRole : '') + (d.kind === 'function' ? '  ·  function' : '') });
      blocks.push({ p: d.explanation });
      const facts = [];
      facts.push('Returns (inferred): ' + d.inferredReturnType);
      if (d.references.length) facts.push('Depends on: ' + d.references.join(', '));
      if (d.unresolvedReferences.length) facts.push('Unresolved: ' + d.unresolvedReferences.join(', '));
      if (d.retrieves.length) facts.push('Resources: ' + d.retrieves.map(r => r.resourceType + (r.valueSet ? ' ["' + r.valueSet + '"]' : '')).join(', '));
      if (d.attributesRead && d.attributesRead.length) facts.push('Attributes read: ' + d.attributesRead.join(', '));
      if (d.timing.phrases.length || d.timing.offsets.length) facts.push('Timing: ' + d.timing.phrases.concat(d.timing.offsets).join(', '));
      facts.push('Source: lines ' + d.sourceStartLine + '–' + d.sourceEndLine);
      blocks.push({ ul: facts });
      if (d.expression) blocks.push({ code: d.expression, lang: 'cql' });
      if (d.booleanLines && d.booleanLines.length) {
        blocks.push({ p: 'Intended logic:' });
        blocks.push({ tree: parseTree(d.booleanLines) });
      }
      if (d.reviewFlags && d.reviewFlags.length) {
        d.reviewFlags.forEach(f => blocks.push({ callout: { kind: f.severity, title: 'Implementation note: ' + f.message, text: f.why } }));
      }
    });

    // Data requirements matrix
    const rows = [];
    a.definitions.forEach(d => {
      d.retrieves.forEach(r => {
        rows.push([d.name, r.resourceType, r.valueSet || '—', (d.attributesRead && d.attributesRead.length) ? d.attributesRead.join(', ') : '—']);
      });
    });
    if (rows.length) {
      blocks.push({ h2: 'Data requirements' });
      blocks.push({ table: { headers: ['Definition', 'Resource', 'Value set', 'Attributes read'], rows: rows } });
    }

    // Dependency order
    blocks.push({ h2: 'Dependencies' });
    const order = topoOrder(a.dependencyGraph);
    blocks.push({ p: 'Suggested evaluation order (dependencies first): ' + (order.length ? order.join(' → ') : 'n/a') });
    if (a.unresolvedReferences.length) {
      blocks.push({ callout: { kind: 'Review', title: 'Unresolved references (' + a.unresolvedReferences.length + ')',
        text: a.unresolvedReferences.map(u => '"' + u.name + '" (referenced by ' + u.from + ', line ' + u.line + ')').join('; ') } });
    }
    a.cycles.forEach(c => blocks.push({ callout: { kind: 'High', title: 'Circular dependency', text: c.join(' → ') } }));

    // Gotchas roll-up
    if (a.reviewFlags.length) {
      blocks.push({ h2: 'Review flags / gotchas' });
      const order2 = { High: 0, Review: 1, Info: 2 };
      a.reviewFlags.slice().sort((x, y) => order2[x.severity] - order2[y.severity]).forEach(f =>
        blocks.push({ callout: { kind: f.severity, title: f.message + (f.line ? ' (' + f.definition + ', line ' + f.line + ')' : ''), text: f.why } }));
    }

    // Not verified
    blocks.push({ h2: 'Not verified (needs a compiler)' });
    blocks.push({ ul: [
      'CQL syntax: ' + a.validation.syntax,
      'Value-set validation: ' + a.validation.valueSetValidation,
      'ELM translation: ' + a.validation.elmTranslation,
      'Execution: ' + a.validation.execution,
      'Specification compliance: ' + a.validation.specificationCompliance,
    ] });

    return { title: title + ' — Engineering Intent Brief', subtitle: 'Engineering brief (draft)', blocks: blocks };
  }

  // --------------------------------------------------------------- utilities
  function uniq(arr) { const s = []; arr.forEach(x => { if (x && s.indexOf(x) === -1) s.push(x); }); return s; }

  function topoOrder(graph) {
    const visited = {}; const out = [];
    function visit(n, stack) {
      if (visited[n] || stack.indexOf(n) !== -1) return;
      (graph[n] || []).forEach(d => { if (d in graph) visit(d, stack.concat(n)); });
      visited[n] = true; out.push(n);
    }
    Object.keys(graph).forEach(n => visit(n, []));
    return out;
  }

  // ============================================================== RENDERERS
  function buildSpec(analysis, mode) {
    return mode === 'engineer' ? buildEngineer(analysis) : buildBusiness(analysis);
  }

  function specToMarkdown(spec) {
    const out = ['# ' + spec.title, '', '_' + spec.subtitle + '_', ''];
    spec.blocks.forEach(b => {
      if (b.h2) out.push('', '## ' + b.h2, '');
      else if (b.h3) out.push('', '### ' + b.h3, '');
      else if (b.p) out.push(b.p, '');
      else if (b.ul) { b.ul.forEach(i => out.push('- ' + i)); out.push(''); }
      else if (b.code) out.push('```' + (b.lang || ''), b.code, '```', '');
      else if (b.tree) { b.tree.forEach(n => out.push('  '.repeat(n.depth) + '- ' + n.text)); out.push(''); }
      else if (b.table) {
        out.push('| ' + b.table.headers.join(' | ') + ' |');
        out.push('| ' + b.table.headers.map(() => '---').join(' | ') + ' |');
        b.table.rows.forEach(r => out.push('| ' + r.map(c => String(c).replace(/\|/g, '\\|')).join(' | ') + ' |'));
        out.push('');
      } else if (b.callout) {
        out.push('> **' + b.callout.kind.toUpperCase() + ': ' + (b.callout.title || '') + '**  ');
        out.push('> ' + b.callout.text, '');
      }
    });
    return out.join('\n');
  }

  const CALLOUT_COLOR = { High: '#f85149', Review: '#d29922', Info: '#58a6ff', note: '#2ea87e' };

  function specToHTML(spec) {
    const out = [];
    spec.blocks.forEach(b => {
      if (b.h2) out.push('<h2>' + esc(b.h2) + '</h2>');
      else if (b.h3) out.push('<h3>' + esc(b.h3) + '</h3>');
      else if (b.p) out.push('<p>' + esc(b.p) + '</p>');
      else if (b.ul) out.push('<ul>' + b.ul.map(i => '<li>' + esc(i) + '</li>').join('') + '</ul>');
      else if (b.code) out.push('<pre class="code"><code>' + esc(b.code) + '</code></pre>');
      else if (b.tree) out.push('<ul class="tree">' + b.tree.map(n => '<li style="margin-left:' + (n.depth * 1.25) + 'rem">' + esc(n.text) + '</li>').join('') + '</ul>');
      else if (b.table) {
        out.push('<div class="tablewrap"><table><thead><tr>' + b.table.headers.map(h => '<th>' + esc(h) + '</th>').join('') + '</tr></thead><tbody>' +
          b.table.rows.map(r => '<tr>' + r.map(c => '<td>' + esc(c) + '</td>').join('') + '</tr>').join('') + '</tbody></table></div>');
      } else if (b.callout) {
        const c = CALLOUT_COLOR[b.callout.kind] || '#8b949e';
        out.push('<div class="callout" style="border-left-color:' + c + '"><div class="callout-title" style="color:' + c + '">' +
          esc(b.callout.kind.toUpperCase()) + (b.callout.title ? ' · ' + esc(b.callout.title) : '') + '</div><div>' + esc(b.callout.text) + '</div></div>');
      }
    });
    return out.join('\n');
  }

  const PRINT_CSS = [
    'body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;max-width:820px;margin:2rem auto;padding:0 1.5rem;line-height:1.55}',
    'h1{font-size:1.6rem;margin:0 0 .25rem}h2{font-size:1.2rem;border-bottom:1px solid #e2e2e2;padding-bottom:.25rem;margin-top:2rem}h3{font-size:1rem;margin-top:1.4rem}',
    '.subtitle{color:#666;margin-bottom:1.5rem}p{margin:.5rem 0}ul{margin:.4rem 0 .8rem;padding-left:1.3rem}ul.tree{list-style:none;padding-left:0}ul.tree li{margin:.15rem 0}',
    'pre.code{background:#f6f8fa;border:1px solid #e2e2e2;border-radius:6px;padding:.75rem;overflow-x:auto;font-size:.82rem;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}',
    'table{border-collapse:collapse;width:100%;font-size:.85rem;margin:.5rem 0}th,td{border:1px solid #ddd;padding:.4rem .6rem;text-align:left;vertical-align:top}th{background:#f6f8fa}.tablewrap{overflow-x:auto}',
    '.callout{background:#fafafa;border-left:4px solid #999;border-radius:0 6px 6px 0;padding:.6rem .9rem;margin:.6rem 0;font-size:.9rem}.callout-title{font-weight:600;margin-bottom:.2rem}',
    '.toolbar{position:sticky;top:0;background:#fff;padding:.5rem 0;border-bottom:1px solid #eee;margin-bottom:1rem}.toolbar button{font-size:.85rem;padding:.4rem .9rem;margin-right:.5rem;cursor:pointer}',
    '@media print{.toolbar{display:none}body{margin:0}}',
  ].join('\n');

  function toStandaloneHTML(spec) {
    return '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
      '<meta name="viewport" content="width=device-width, initial-scale=1">' +
      '<title>' + esc(spec.title) + '</title><style>' + PRINT_CSS + '</style></head><body>' +
      '<div class="toolbar"><button onclick="window.print()">Print / Save as PDF</button></div>' +
      '<h1>' + esc(spec.title) + '</h1><div class="subtitle">' + esc(spec.subtitle) + '</div>' +
      specToHTML(spec) + '</body></html>';
  }

  return {
    buildSpec: buildSpec,
    specToMarkdown: specToMarkdown,
    specToHTML: specToHTML,
    toStandaloneHTML: toStandaloneHTML,
    _internals: { buildBusiness: buildBusiness, buildEngineer: buildEngineer, topoOrder: topoOrder, parseTree: parseTree },
  };
});
